version: '3.9'  # version 3.9 or later is required to use the platform directive
services:
  kali:
    image: r1cs3c/kali_default_xrdp
    platform: linux/amd64
    ports:
      - "3389:3389"
      - "3350:3350"
    command: ["/bin/bash", "-c", "service xrdp restart; tail -f /dev/null"]
