Description: 'Cochlear ECR template'

Parameters:
  RepositoryName:
    Description: Name of the repository
    Type: String
    Default: cochlear-drx-node
  Project:
   Description: the name for the project
   Type: String
   Default: cloud-engineering
  Environment:
   Description: The environment for the project
   Type: String
   Default: nonp
Conditions:
  UseCustomRepositoryName:
    Fn::Not:
      - Fn::Equals:
        - !Ref RepositoryName
        - ""
Resources:
    MyRepository:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: 
                Fn::If: 
                    -  UseCustomRepositoryName
                    -  !Ref RepositoryName
                    -  !Sub cochlear-${Project}-${Environment}
            ImageScanningConfiguration:
                ScanOnPush: "true"
            RepositoryPolicyText: 
                Version: "2012-10-17"
                Statement: 
                - 
                    Sid: AllowPushPull
                    Effect: Allow
                    Principal: 
                        AWS: 
                            - !Join [':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'root']]
                    Action: 
                    - "ecr:GetDownloadUrlForLayer"
                    - "ecr:BatchGetImage"
                    - "ecr:BatchCheckLayerAvailability"
                    - "ecr:PutImage"
                    - "ecr:InitiateLayerUpload"
                    - "ecr:UploadLayerPart"
                    - "ecr:CompleteLayerUpload"
            Tags:
                - Key: Project
                  Value: !Ref Project
                - Key: Environment
                  Value: !Ref Environment     
            LifecyclePolicy:
                LifecyclePolicyText: |
                    {
                        "rules": [
                            {
                                "rulePriority": 1,
                                "description": "Production Image keep 10",
                                "selection": {
                                    "tagStatus": "tagged",
                                    "tagPrefixList": ["PRD"],
                                    "countType": "imageCountMoreThan",
                                    "countNumber": 10
                                },
                                "action": { "type": "expire" }
                            },
                            {
                                "rulePriority": 2,
                                "description": "UAT Image keep 2",
                                "selection": {
                                    "tagStatus": "tagged",
                                    "tagPrefixList": ["UAT"],
                                    "countType": "imageCountMoreThan",
                                    "countNumber": 5
                                },
                                "action": { "type": "expire" }
                            },
                            {
                                "rulePriority": 3,
                                "description": "SIT Image keep 2",
                                "selection": {
                                    "tagStatus": "tagged",
                                    "tagPrefixList": ["SIT"],
                                    "countType": "imageCountMoreThan",
                                    "countNumber": 2
                                },
                                "action": { "type": "expire" }
                            },
                            {
                                "rulePriority": 4,
                                "description": "DEV Image keep 1",
                                "selection": {
                                    "tagStatus": "tagged",
                                    "tagPrefixList": ["DEV"],
                                    "countType": "imageCountMoreThan",
                                    "countNumber": 1
                                },
                                "action": { "type": "expire" }
                            },
                            {
                                "rulePriority": 5,
                                "description": "untage Image keep 0",
                                "selection": {
                                    "tagStatus": "untagged",
                                    "countType": "sinceImagePushed",
                                    "countUnit": "days",
                                    "countNumber": 1
                                },
                                "action": { "type": "expire" }
                            }                           
                        ]
                    }