Description: 'Cochlear ECS template'

Parameters:
  ECSName:
    Description: Name of the ECS with environment
    Type: String
    Default: cochlear-authnz-dev
  Project:
   Description: the name for the project
   Type: String
   Default: cloud-engineering
  Environment:
   Description: The environment for the project
   Type: String
   Default: nonp
Conditions:
  UseCustomECSName:
    Fn::Not:
      - Fn::Equals:
        - !Ref ECSName
        - ""
Resources:
    ECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
          ClusterName: 
            Fn::If: 
              -  UseCustomECSName
              -  !Ref ECSName
              -  !Sub cochlear-${Project}-${Environment}
          Tags:
            - Key: Project
              Value: !Ref Project
            - Key: Environment
              Value: !Ref Environment            
Outputs:
    ECSClusterInfo:
        Value:
            Ref: ECSCluster
    