---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cochlear DRX Route53 A Record Alias v1'
Parameters:
  RecordName:
    Type: String
    Description: Record name of DNS entry
  CFRecordName:
    Type: String
    Description: Record name of DNS entry
  ALBRecordName:
    Type: String
    Description: ALB DNS Record Name
  CreateCFDNSRecord:
    Type: String
    Description: Select True if you would like to create an cf dns record name
    Default: false
    AllowedValues:
    - true
    - false
    ConstraintDescription: must be one of true or false
  CFDomain:
    Type: String
    Description: CF Domain
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: "(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)"
    ConstraintDescription: must be a valid DNS zone name.
Mappings:
  loadBalanceHostedZone:
    us-east-1:
      id: Z35SXDOTRQ7X7K
    us-east-2:
      id: Z3AADJGX6KTTL2
    us-west-1:
      id: Z368ELLRRE2KJ0
    us-west-2:
      id: Z1H1FL5HABSF5
    ap-south-1:
      id: ZP97RAFLXTNZK
    ap-northeast-1:
      id: Z14GRHDCWA56QT
    ap-northeast-2:
      id: ZWKZPGTI48KDX
    ap-northeast-3:
      id: Z5LXEXXYW11ES
    ap-southeast-1:
      id: Z1LMS91P8CMLE5
    ap-southeast-2:
      id: Z1GM3OXH4ZPM65
    eu-west-1:
      id: Z32O12XQLNTSW2
    eu-west-2:
      id: ZHURV8PSTC4K8
    eu-west-3:
      id: Z3Q77PNBQS71R4
Conditions:
  CreateCFDNSRecord:
    Fn::Equals:
    - Ref: CreateCFDNSRecord
    - true
Resources:
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Ref: ALBRecordName
        HostedZoneId:
          Fn::FindInMap:
          - loadBalanceHostedZone
          - Ref: AWS::Region
          - id
      HostedZoneName:
        Fn::Join:
        - ''
        - - Ref: HostedZone
          - "."
      Comment: Cochlear Website Record.
      Name:
        Fn::Join:
        - ''
        - - Ref: RecordName
          - "."
          - Ref: HostedZone
          - "."
      Type: A
  CFDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateCFDNSRecord
    Properties:
      HostedZoneName:
        Fn::Join:
        - ''
        - - Ref: HostedZone
          - "."
      Comment: Cochlear Website Record.
      Name:
        Fn::Join:
        - ''
        - - Ref: CFRecordName
          - "."
          - Ref: HostedZone
          - "."
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - Ref: CFDomain
Outputs:
  DomainName:
    Description: Fully qualified domain name
    Value:
      Ref: DNSRecord
    Export:
      Name:
        Fn::Join:
        - ":"
        - - Ref: AWS::StackName
          - DomainName
  CFDomainName:
    Description: Fully qualified cf cname
    Value:
      Ref: CFDNSRecord
    Condition: CreateCFDNSRecord
    Export:
      Name:
        Fn::Join:
        - ":"
        - - Ref: AWS::StackName
          - CFDomainName
