AWSTemplateFormatVersion: 2010-09-09
Description: 'Cochlear Regional Managed Rule v1'

Parameters:
  WAFDescription:
    Type: String
    Description: Description shown on the WAF
    Default: Regional WAF with no IP set
  WAFName:
    Type: String
    Description: Name shown on the WAF
    Default: RegionalWAFV2
Resources:
  WebACLWithAMR:
    Type: AWS::WAFv2::WebACL
    Properties:
      Scope: REGIONAL
      Name: !Ref WAFName
      Description: !Ref WAFDescription
      DefaultAction: 
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: MetricForWebACLWithAMR
      Rules: 
        - Name: ip-flood-rule
          Priority: 2
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForIPFloodRule
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 2000   
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRCRS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet

        - Name: AWS-AWSManagedAdminProtectionRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRAPS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAdminProtectionRuleSet

        - Name: AWS-AWSManagedKnownBadInputsRuleSet
          Priority: 5
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRKBIRS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet

        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 6
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRIRLRS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList

        - Name: AWS-AWSManagedRulesLinuxRuleSet
          Priority: 7
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRLRS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet

        - Name: AWS-AWSManagedRulesUnixRuleSet
          Priority: 8
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForAMRURS
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet           
                  
Outputs:
  WAFWebACL:
    Description: AWS WAF WebACL
    Value: !Ref WebACLWithAMR
  WAFWebACLID:
    Description: AWS WAF WebACL ID
    Value: !GetAtt WebACLWithAMR.Id
  WAFWebACLARN:
    Description: AWS WAF WebACL Arn
    Value: !GetAtt WebACLWithAMR.Arn
